using Microsoft.AspNetCore.Authentication.JwtBearer;
using Asp.Versioning;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi;

var builder = WebApplication.CreateBuilder(args);

// Setup paramemeters to verify jwt in cognito
// Cognito config values are in appsettings.json. 
var awsRegion = builder.Configuration["Cognito:Region"]
    ?? throw new InvalidOperationException("Cognito Region is missing. Make sure it exists in appsettings.json");

var userPoolId = builder.Configuration["Cognito:UserPoolId"]
    ?? throw new InvalidOperationException("Cognito UserPoolId is missing. Make sure it exists in appsettings.json");

var appClientId = builder.Configuration["Cognito:ClientId"]
    ?? throw new InvalidOperationException("Cognito ClientId is missing. Make sure it exists in appsettings.json");

var authority = $"https://cognito-idp.{awsRegion}.amazonaws.com/{userPoolId}";

builder.Services.AddUsers(builder.Configuration);
builder.Services.AddBusinesses(builder.Configuration);
builder.Services.AddAgreements(builder.Configuration);
builder.Services.AddKyc(builder.Configuration);

builder.Services.AddApiVersioning(options =>
{
    options.DefaultApiVersion = new ApiVersion(1, 0);
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.ReportApiVersions = true;
    options.ApiVersionReader = new UrlSegmentApiVersionReader();
})
.AddMvc()
.AddApiExplorer(options =>
{
    options.GroupNameFormat = "'v'VVV";
    options.SubstituteApiVersionInUrl = true;
});

// These lines setup JWT verification
builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.MapInboundClaims = false;
    options.Authority = authority; // ASP.NET Core auto-discovers JWKS from here
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidIssuer = authority,
        ValidateAudience = true,
        ValidAudience = appClientId,
        ValidateLifetime = true,
    };

    // DEBUG: To troubleshoot jwt events
    // options.Events = new JwtBearerEvents
    // {
    //     OnAuthenticationFailed = context =>
    //     {
    //         Console.WriteLine($"Token validation failed: {context.Exception.Message}");
    //         return Task.CompletedTask;
    //     }
    // };
});

builder.Services.AddAuthorization();
builder.Services.AddControllers();

// CORS: allow the frontend origin(s) from appsettings.json to call the API.
// The Authorization header is covered by AllowAnyHeader; AllowCredentials is
// included for cookie based auth (if we ever add session cookies).
builder.Services.AddCors(options =>
{
    options.AddPolicy("Frontend", policy =>
    {
        var origins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>()
            ?? [];

        policy.WithOrigins(origins)
              .AllowAnyMethod()
              .AllowAnyHeader()
              .AllowCredentials();
    });
});

// configure swagger
builder.Services.AddSwaggerGen(options =>
{
    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
        In = ParameterLocation.Header,
        Description = "Paste your JWT token below (no need to type 'Bearer')."
    });

    options.AddSecurityRequirement(document => new OpenApiSecurityRequirement
    {
        [new OpenApiSecuritySchemeReference("Bearer", document)] = []
    });

    options.SupportNonNullableReferenceTypes();
    options.UseAllOfToExtendReferenceSchemas(); 
});

var app = builder.Build();


// DEBUG: Shows the authorization header that was received

// app.Use(async (context, next) =>
// {
//     Console.WriteLine($"Authorization header received: {context.Request.Headers["Authorization"]}");
//     await next();
// });

// For security reasons, this conditional ensures that the API documentation generated by swagger
// is only displayed in development environment
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint("/swagger/v1/swagger.json", "Yami API v1");
    });
}

// CORS must run BEFORE authentication: the browser's preflight (OPTIONS)
// request carries no Authorization header, so if auth ran first the
// preflight would be rejected with 401 and the real request would never fire.
app.UseCors("Frontend");

app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

app.Run();