version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dotnet"
    reviewers:
      - "ajadimayowa"
      - "AdewaleOpeloyeru"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "ajadimayowa"
      - "AdewaleOpeloyeru"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"
      include: "scope"
