name: Build

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build.yaml'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Check .NET SDK version
        run: dotnet --version