name: Build

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/build.yaml'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.7.0
        with:
          versionSpec: '6.8.x'

      - name: Execute Git Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.7.0

      # - name: Display Build SemVer
      #   run: |
      #     echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
      #     echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
      #     echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"

      - name: Set Build Version
        env:
          BRANCH: ${{ github.ref_name }}
          BASE_VERSION: ${{ steps.gitversion.outputs.majorMinorPatch }}
        run: |
          if [ "${BRANCH}" != "main" ]; then
            BUILD_VERSION="${BASE_VERSION}-$(date +'%Y%m%d-%H%M%S')"
          else
            BUILD_VERSION="${BASE_VERSION}"
          fi
          echo "build version: ${BUILD_VERSION}"
          echo "BUILD_VERSION=${BUILD_VERSION}" >> "$GITHUB_ENV"

      - name: Check .NET SDK Version
        run: dotnet --version

      - name: Download Dependencies
        run: dotnet restore

      - name: Build Code
        run: dotnet build

      - name: DotNet Publish
        run: |
          dotnet publish src/Yami.Api/Yami.Api.csproj \
          -c Release \
          --self-contained false \
          -o publish

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: yamicredit/yami/yamibackend:${{env.BUILD_VERSION}}